apiVersion: v2
name: kube-cost-metrics-collector
version: 0.1.3
description: Costimizer Kubernetes metrics collector.
type: application
dependencies:
  - name: prometheus
    version: "17.0.2"
    repository: https://prometheus-community.github.io/helm-charts
  - name: kube-service-selectors
    version: "1.0.2"
    repository: https://costimizerinc.github.io/helm-charts
maintainers:
  - name: Costimizer
    email: contact@costimizer.ai
